[project]
name = "python30hari"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
]

[tool.uv.workspace]
members = [
    "Day1",
    "Hari2",
]
